runtime: nodejs14 

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  NODE_ENV: 'production'

handlers:
- url: /static
  static_dir: build/static
  
- url: /.*
  static_files: build/index.html
  upload: build/index.html
 